site_name: DefiTuna Analytics
site_url: https://example.com/analytics
repo_url: https://github.com/defituna/analytics
repo_name: DefiTuna Analytics
edit_uri: ''
theme:
  name: material
  language: en
  font:
    text: Inter
    code: JetBrains Mono
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - content.code.annotate
    - toc.integrate
nav:
  - Home: index.md
  - DefiTuna:
      - Overview: defituna/overview.md
  - Analytics (interactive): interactive.md
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - md_in_html
extra:
  analytics_bundle_path: analytics/index.html
  data_manifest: data/_manifest.json
extra_css:
  - stylesheets/site.css
  - stylesheets/analytics.css
extra_javascript:
  - javascripts/site.js
  - analytics/vendor/plotly-3.1.0.min.js
  - javascripts/treasury-dashboard.js
